repos:
- repo: https://github.com/PyCQA/isort
  rev: '6.0.0'
  hooks:
  - id: isort
    args:
      - --check-only
      - --recursive
      - --settings-path
      - ./setup.cfg
      - .
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v0.9.1
  hooks:
  - id: flake8
    args:
      - --ignore=E501,F401,E128,E402,E731,F821